## Key2

对于病理的任务，将病理的所有tiles转化成histogram或者tfidf的patient特征。

![](http://www.medai.icu/storage/attachments/2022/06/26/n41q4HeDjvIOZnyfoKH28c5YNioGdB7OZwO35XOf.png)

参考论文: [Development and interpretation of a pathomics-based model for the prediction of microsatellite instability in Colorectal Cancer](http://www.medai.icu/download?url=http://www.medai.icu/apiv3/attachment.download?sign=1667478d908313ae1e01543e229d02de&attachmentsId=1061&threadId=230)

In [2]:
import pandas as pd
from onekey_algo.custom.utils import key2
import numpy as np
import os

os.makedirs('features', exist_ok=True)
log = pd.read_csv(r'results/ALL_DL_PREDICTIONS.csv')
log.columns = ['group', 'prob', 'pred', 'gt']
log['prob'] = log['prob'].round(decimals=2)

results = key2.key2histogram(log, group_column='group',histo_columns='prob', norm=True)
results.to_csv('features/prob_histogram.csv', header=True, index=False)
display(results)

results = key2.key2histogram(log, group_column='group',histo_columns='pred', norm=True)
results.to_csv('features/pred_histogram.csv', header=True, index=False)
display(results)

results = key2.key2tfidf(log, group_column='group',corpus_columns='prob')
results.to_csv('features/prob_tfidf.csv', header=True, index=False)
display(results)

results = key2.key2tfidf(log, group_column='group',corpus_columns='pred')
results.to_csv('features/pred_tfidf.csv', header=True, index=False)
display(results)

[2025-09-12 20:29:25 - key2.py:  59]	INFO	一共有291个样本。

,ID,prob-0.0,prob-0.01,prob-0.02,prob-0.03,prob-0.04,prob-0.05,prob-0.06,prob-0.07,prob-0.08,...,prob-0.91,prob-0.92,prob-0.93,prob-0.94,prob-0.95,prob-0.96,prob-0.97,prob-0.98,prob-0.99,prob-1.0
0,J07A0929,0.025,0.040,0.050,0.045,0.060,0.070,0.070,0.050,0.020,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
1,J07A0930,0.003,0.013,0.026,0.017,0.036,0.023,0.030,0.043,0.050,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
2,J07A0933,0.000,0.000,0.004,0.008,0.000,0.004,0.023,0.008,0.017,...,0.008,0.008,0.004,0.002,0.004,0.01,0.002,0.015,0.002,0.0
3,J07A0934,0.000,0.000,0.010,0.021,0.082,0.021,0.031,0.000,0.010,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
4,J07A0935,0.007,0.028,0.028,0.025,0.051,0.044,0.048,0.046,0.042,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
286,J07A3189,0.000,0.043,0.065,0.065,0.076,0.098,0.130,0.033,0.098,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
287,J07A3190,0.035,0.153,0.131,0.066,0.114,0.061,0.074,0.035,0.070,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
288,J07A3191,0.531,0.113,0.047,0.031,0.039,0.016,0.027,0.016,0.016,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
289,J07A3192,0.449,0.251,0.106,0.048,0.039,0.014,0.014,0.010,0.000,...,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0
290,J07A3193,0.202,0.163,0.085,0.062,0.043,0.019,0.031,0.019,0.019,...,0.000,0.004,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.0

[2025-09-12 20:29:27 - key2.py:  59]	INFO	一共有291个样本。

           ID  pred-0  pred-1
0    J07A0929   0.985   0.015
1    J07A0930   0.970   0.030
2    J07A0933   0.599   0.401
3    J07A0934   0.959   0.041
4    J07A0935   0.982   0.018
..        ...     ...     ...
286  J07A3189   1.000   0.000
287  J07A3190   0.991   0.009
288  J07A3191   0.992   0.008
289  J07A3192   1.000   0.000
290  J07A3193   0.853   0.147

[291 rows x 3 columns]

,ID,prob00,prob001,prob002,prob003,prob004,prob005,prob006,prob007,prob008,...,prob091,prob092,prob093,prob094,prob095,prob096,prob097,prob098,prob099,prob10
J07A0929,J07A0929,0.136,0.198,0.246,0.219,0.292,0.340,0.337,0.245,0.098,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A0930,J07A0930,0.020,0.071,0.141,0.088,0.193,0.123,0.156,0.229,0.264,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A0933,J07A0933,0.000,0.000,0.019,0.037,0.000,0.018,0.100,0.037,0.074,...,0.143,0.141,0.077,0.036,0.073,0.193,0.043,0.276,0.046,0.0
J07A0934,J07A0934,0.000,0.000,0.046,0.091,0.365,0.091,0.135,0.000,0.046,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A0935,J07A0935,0.041,0.150,0.149,0.135,0.270,0.233,0.255,0.247,0.222,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
J07A3189,J07A3189,0.000,0.172,0.256,0.253,0.295,0.380,0.501,0.127,0.382,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A3190,J07A3190,0.137,0.546,0.464,0.229,0.398,0.214,0.257,0.123,0.246,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A3191,J07A3191,0.971,0.189,0.077,0.051,0.064,0.025,0.044,0.026,0.026,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A3192,J07A3192,0.869,0.443,0.185,0.083,0.067,0.025,0.025,0.017,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
J07A3193,J07A3193,0.699,0.514,0.267,0.192,0.132,0.060,0.095,0.060,0.060,...,0.000,0.046,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0

                ID  pred0  pred1
J07A0929  J07A0929  1.000  0.018
J07A0930  J07A0930  0.999  0.037
J07A0933  J07A0933  0.779  0.627
J07A0934  J07A0934  0.999  0.052
J07A0935  J07A0935  1.000  0.023
...            ...    ...    ...
J07A3189  J07A3189  1.000  0.000
J07A3190  J07A3190  1.000  0.011
J07A3191  J07A3191  1.000  0.009
J07A3192  J07A3192  1.000  0.000
J07A3193  J07A3193  0.979  0.204

[291 rows x 3 columns]